services:
  # 1. Usługa aplikacji Python
  app:
    build: .
    container_name: os-ww-p
    restart: unless-stopped
    volumes:
      - .:/app
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=" "
      - MYSQL_DATABASE=search_db
    depends_on:
      - db

  # 2. Usługa serwera Apache
  apache:
    image: httpd:2.4
    container_name: apache_server
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./apache.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
    depends_on:
      - app # Poprawiona nazwa usługi

  # 3. Usługa bazy danych MySQL
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql

# Definicja nazwanego woluminu
volumes:
  mysql_data: